services:
  servidor:
    image: servidor
    build: .
    ports:
      - "80:8000"
    links:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "info"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
