services:
  servidor:
    image: servidor
    build: .
    ports:
      - "80:80"
    links:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "info"
      # So you don't have to use root, but you can if you like
      # You can use whatever password you like
      MYSQL_PASSWORD: "sa2023"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
